### PR TITLE
update api to use newer 'electron' module

### PR DESCRIPTION
**Pull request by jcblw**
Hey just opening this up to fix the module in newer builds of electron. I was wondering if there is plans to support older versions or if `latest` of electron is the main target for this module? LMK I can revise the PR based off the feed back.

And thanks for the module 🎉

### CODE REVIEW

**Comment by knpwrs** [comment]
I'll probably merge this, add greenkeeper, and target `latest`.

**Comment by jcblw** [comment]
lmk if there is anything i can do to help 🤓

**Comment by knpwrs** [comment]
Sorry, I've been at a conference. I'm going to merge and check a few things.

**Comment by knpwrs** [comment]
Published as `2.0.0`.

**Comment by jcblw** [comment]
💪 awesome thanks

**Pull request merged**
